services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/etl/db/raw/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: api_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
