services:
  backend:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: api_backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend
